import glob
import os
import logging
from pathlib import Path


################################################################################
# logger
logger = logging.getLogger("palette-creator")
logger.setLevel(logging.INFO)
ConsoleOutputHandler = logging.StreamHandler()
logger.addHandler(ConsoleOutputHandler)

################################################################################
# constants
README_HEADER = """# C4-PlantUML-Themes

C4-PlantUML-Themes autogenerated from ColorBrewer and Seaborn palettes. See the C4-Plant UML [Themes](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/Themes.md) page for more information on the variables set by each theme.

Usage:

```

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' START - Handle local PlantUML render and remote hosting
'
!$THEME_NAME = cb_div_RdGy_9
'
!if (%getenv("LOCAL_EDIT_BLOG_ROOT") == "")
!$THEME_ROOT_PATH = "https://YOUR_HOSTNAME/resources/"
!else
!$THEME_ROOT_PATH = %getenv("LOCAL_EDIT_BLOG_ROOT") + "/resources/"
!endif
!define INCLUDE(a,b) ##a##b

' Define the theme name we're going to use
!if (%getenv("LOCAL_EDIT_BLOG_ROOT") == "")
!theme $THEME_NAME from https://YOUR_HOSTNAME/resources/palettes
!else
!theme $THEME_NAME from resources/palettes
!endif

!include INCLUDE($THEME_ROOT_PATH, c4-theme-common.puml)
' END - Handle local PlantUML render and remote hosting
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
```

where _c4-theme-common.puml_ is as follows (depends on [PlantUML PR 295](https://github.com/plantuml-stdlib/C4-PlantUML/pull/295) or later):

```
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4.puml)
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4_Component.puml)
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4_Container.puml)
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4_Context.puml)
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4_Deployment.puml)
!include INCLUDE($THEME_ROOT_PATH, C4-PlantUML/C4_Dynamic.puml)

skinparam DefaultFontName Open Sans
skinparam Handwritten false
skinparam TitleFontSize 24
```


The generated theme files are below:
"""

################################################################################
# main
readme_text = README_HEADER
theme_files = glob.glob("./palettes/*.puml")
theme_files.sort()
for each_file in theme_files:
    logger.info("Checking file: %s", each_file)
    path_base = each_file.removesuffix(".puml")
    file_palette_path = path_base + ".png"
    file_preview_path = path_base + "-example.png"
    file_basename = Path(each_file).name

    readme_section = """
## {0}

| Palette  | Image |
| ------------- | ------------- |
| [![{1}]({1})]({2})  | [![{3}]({3})]({2})  |

""".format(
        file_basename, file_palette_path, each_file, file_preview_path
    )
    readme_text += readme_section

    with open("README.md", "w") as readme_output:
        readme_output.write(readme_text)
