import glob
import os
import logging
from pathlib import Path


################################################################################
# logger
logger = logging.getLogger("palette-creator")
logger.setLevel(logging.INFO)
ConsoleOutputHandler = logging.StreamHandler()
logger.addHandler(ConsoleOutputHandler)

################################################################################
# constants
README_HEADER = """# C4-PlantUML-Themes

C4-PlantUML-Themes autogenerated from ColorBrewer and Seaborn palettes

The generated theme files are below:
"""

################################################################################
# main
readme_text = README_HEADER
theme_files = glob.glob("./palettes/*.puml")
for each_file in theme_files:
  logger.info("Checking file: %s", each_file)
  path_base = each_file.removesuffix(".puml")
  file_imagepath = path_base + ".png"
  file_basename = Path(each_file).name

  readme_section = """
## {0}

[![{1}]({1})]({2})
""".format(file_basename, file_imagepath, each_file)
  readme_text += readme_section

  with open("README.md", "w") as readme_output:
      readme_output.write(readme_text)
